#!/bin/sh

# Set source and target directories
powerline_fonts_dir="$( cd "$( dirname "$0" )" && pwd )"

# Set a prefix to pick a certain font, if none provided all fonts will be installed.
prefix="$1"

# Set FontBook location
if [[ "$(uname)" = "Darwin" ]]
then
  # MacOS
  font_dir="$HOME/Library/Fonts"
else
  # Linux
  font_dir="$HOME/.local/share/fonts"
  mkdir -p $font_dir
fi

# Install into FontBook directories
echo "Copying fonts..."
find "$powerline_fonts_dir" \( -name "$prefix*.[ot]tf" -or -name "$prefix*.pcf.gz" \) -type f -print0 | xargs -0 -n1 -I % cp "%" "$font_dir/"

# Reset font cache on Linux
if [[ "$(uname)" != "Darwin" ]]
then
  echo "Resetting font cache, this may take a moment..."
  fc-cache -f "$font_dir"
fi

echo "Powerline fonts installed to $font_dir"
